### ISSUE TITLE
COMPAT: numpy compat

### ISSUE THREAD

**Issue by jreback** [libdynd/dynd-python#149]
Here are some numpy compat issues that I have come across on adding IntNA support in pandas:

where ``arr`` is say ``nd.array([1,2,3],type='3 * ?int32')``

- [x] ``arr.ndim``  (though ``len(arr.shape)`` works)
- [ ] ``arr.view()`` (though ``nd.view(arr)`` works)
- [ ] ``arr.base`` for the view reference (or something analagous)?
- [ ] ``nd.array()`` does not take the ``copy=`` argument
- [x] ``arr.dtype`` (requires ``nd.type_of(arr).dtype`` to work)
- [ ] ``nd.type_of(arr).dtype.type`` (need to use ``nd.type_of(arr).dtype.value_type``)
- [ ] ``nd.isnan()/nd.isna()`` (NA testing)
- [ ] define ``__iter__`` on nd.array
- [ ] ``ndt.type('?int32').name`` should return ``ndt.type('?int32').dshape`` (for numpy compat)

I will add more as I continue to dig

**Comment by jreback** [comment]
In numpy I can use ``.base`` attribute to see if its a view

```
In [17]: x = np.array([1,2,3])

In [18]: x.base

In [19]: x.view('i8').base
Out[19]: array([1, 2, 3])
```

How do I do this in dynd?
(side issue is we want to support the ``.view()`` function and ``.base`` attributes to do this for compat
```
In [20]: from dynd import nd

In [23]: import dynd

In [24]: dynd.__version__
Out[24]: '0.6.6.post084.gdc3bbe5'

In [25]: y = nd.array([1,2,3])

In [26]: nd.view(y)             
Out[26]: 
nd.array([1, 2, 3],
         type="3 * int32")
```

**Comment by izaid** [comment]
I don't think this is implemented right now, either in Python or C++, but it should be easy to add something. Let's let @mwiebe weigh in.

**Comment by mwiebe** [comment]
This mechanism isn't really reliable in NumPy, so I was kind of hesitant to proceed with matching it when thinking about it before. For example, NumPy has operations which create an array, then do some stride manipulation of it into a view, then return that view, so that the "view" is the primary owner of the data as far as all code is concerned but looks like a view with this test.

Something quite similar to the "base" attribute could be rigged up, but I think it might be even less reliable than NumPy's. Here's how a new array + view operation would look:

1. Create a new array X, which allocates data buffer B consists of: (numpy wrapper N1 -> dynd array D1 -> (ref to B, pointer to B's memory).

2. Create a view of X, which creates a new numpy wrapper and dynd wrapper, otherwise the same: (numpy wrapper N2 ->dynd array D2 -> (ref to B, pointer to B's memory). To avoid long chains of references, which can cause performance stutters when freeing under some circumstances, the reference is made to the data owner, and hence both N1 and N2 look identical from the outside,

There's no way to say that "N1 owns the data, but N2 is a view", because the data is owned by a separate lightweight object B that has no Python wrapper, etc.

There are some cases, for efficiency,  where B is equal to N1 as a performance optimization, but this is not something guaranteed, and I think it's best for libdynd to reserve the right to change that interface for performance/other reasons. This latter bit is what I meant by being able to rig something up, but it being less reliable than NumPy.

**Comment by mwiebe** [comment]
A close thing might  be a test like "dynd allocated this array, and there are no other views into its data", which can be done by checking what kind of buffer B is, and whether any embedded reference counts are greater than one.

**Comment by jreback** [comment]
I use this to determine if the data is attached to another view, e.g.

```
x1 = np.array([1,2,3])
x2 = x1[1:2]
```
```
x2[0] = 5
```
In certain circumstances we care that this modification is happening (not in this 1-d case, but in a 2-d case, where we have a view into part of a structure that is being modified on a copy of the data).

So for compat if you DO have a refcount, that would be very helpful, so all I would care about was
``arr.refcount > 1`` (meaning that at least 1 view exists). I understand you are not tracking views (nor should you), but I think this would suffice (and maybe make ``arr.base`` could then be a simple property (for compatibility), e.g.

```
@property
def base(self):
   if self.refcount == 1:
      return None
   return self
```

**Comment by jreback** [comment]
closing this, will make a new list based on current dynd
