### ISSUE TITLE
Experiences with weather data

### ISSUE THREAD

**Issue by mrocklin** [libdynd/dynd-python#384]
I'm trying to munge data from a weather API.  It's somewhat predictable nested JSON.

I'm running into a few problems because the JSON includes some missing values from time to time.  This gist holds both a notebook and the relevant data.

https://gist.github.com/mrocklin/621e810f9c38931d37fd

For the moment I'm still stuck using python's `datashape.discover` because it will unite the records in the hourly field.  Apparently the datashape is wrong in some way but I can't see how.

**Comment by izaid** [comment]
Okay, so the problem here is 2 little bugs that are totally unrelated to JSON.

1) Apparently, DyND currently has an issue with '-' in struct names. I'll fix this, but if you can remove the '-' from "isd-stations" that would be good.

2) parse_json actually takes the type then the JSON blob -- try x = nd.parse_json(ds, s)

**Comment by mrocklin** [comment]
Verified that this resolves things.
